name: build and push docker images

on:
  push:
    tags:
      - '*'

jobs:

  build-and-push-test-fybrik-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push test-fybrik Image
        uses: ./.github/actions/build-and-push
        with:
          path-to-image: docker/test-fybrik.Dockerfile
          repository: ghcr.io/twlabs/test-fybrik
          github-token: ${{ secrets.GITHUB_TOKEN }}
